# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [2]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [3]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
lst[2:3]

[3]

In [6]:
arr[2:3]

array([3])

In [7]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [8]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr[-1] = 1.23234
arr

array([1, 2, 3, 4, 1])

In [11]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [12]:
adoring_bootharr = np.arange(1e7)  

In [13]:
lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [14]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [14]:
%timeit arr * 1.1

1.48 µs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit lst_multiplicacion(lst, 1.1)

394 ns ± 7.57 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creación de arrays

In [15]:
arr

array([1, 2, 3, 4, 1])

In [16]:
arr = np.arange(10,21)

In [17]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
arr = np.zeros(5)

In [19]:
arr

array([0., 0., 0., 0., 0.])

In [20]:
arr = np.linspace(0,1,100)

In [21]:
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [22]:
arr = np.logspace(0,1,100, base=10)

In [23]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [24]:
arr2d = np.zeros((5,5))

In [25]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [27]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [28]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [29]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [30]:
cubo.dtype

dtype('float16')

In [31]:
np.empty((2,3,4))

array([[[4.65108952e-310, 0.00000000e+000, 6.94360298e-310,
         6.94360298e-310],
        [6.94360298e-310, 6.94360298e-310, 6.94360298e-310,
         6.94360298e-310],
        [6.94360298e-310, 6.94360298e-310, 6.94360298e-310,
         6.94360298e-310]],

       [[6.94360298e-310, 6.94360298e-310, 6.94360298e-310,
         6.94360298e-310],
        [6.94360298e-310, 6.94360298e-310, 6.94360298e-310,
         6.94360298e-310],
        [6.94360298e-310, 6.94360298e-310, 6.94360298e-310,
         6.94360298e-310]]])

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.rand(3)

array([0.09490962, 0.73506455, 0.2004472 ])

## Reshaping

In [34]:
arr = np.arange(1000)

In [35]:
arr3d = arr.reshape((10,10,10))

In [36]:
arr3d.ndim

3

In [37]:
arr3d.shape

(10, 10, 10)

In [38]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [39]:
arr = np.arange(200)

In [40]:
arr2d = arr.reshape((10,20))

In [41]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Aplanar

In [42]:
arr = np.zeros((4,4,4,4))

In [43]:
arr.shape

(4, 4, 4, 4)

In [44]:
arr_plano = arr.ravel()

In [46]:
arr_plano.shape

(256,)

In [47]:
arr_plano

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

## *Broadcasting*

In [48]:
data = np.array([1,2,3,4,5])

In [49]:
data

array([1, 2, 3, 4, 5])

In [50]:
data + 1

array([2, 3, 4, 5, 6])

In [51]:
data * 2

array([ 2,  4,  6,  8, 10])

In [52]:
data ** 2

array([ 1,  4,  9, 16, 25])

## Transponer

In [53]:
arr = np.arange(15).reshape((3,5))

In [54]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [56]:
arr  = np.arange(16).reshape((2,2,4))

In [57]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [58]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [59]:
arr = np.arange(10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [61]:
arr_slice =  arr[5:8]

In [62]:
arr_slice

array([5, 6, 7])

In [63]:
arr_slice[1]= 12345678

In [64]:
arr_slice

array([       5, 12345678,        7])

In [65]:
arr

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [66]:
arr_slice[:] = 345

In [67]:
arr_slice

array([345, 345, 345])

In [68]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [69]:
arr2 = np.copy(arr)

In [70]:
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [71]:
arr2[5:8] = [5,6,7]

In [72]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [74]:
np.may_share_memory(arr, arr_slice)

True

In [75]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [76]:
arr = np.arange(9)

In [77]:
arr.shape = (3,3)

In [78]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
arr.ndim

2

In [80]:
arr[2]

array([6, 7, 8])

In [81]:
arr[-1]

array([6, 7, 8])

In [82]:
arr[1][1]

4

In [83]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [84]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
arr[:1,:2]

array([[0, 1]])

In [86]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [88]:
arr[1:,]

array([[3, 4, 5],
       [6, 7, 8]])

In [89]:
arr[1,:2]

array([3, 4])

In [90]:
arr[1,2:]

array([5])

In [91]:
arr[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [92]:
arr[:,:1] 1,  1,  1,  1,  1]

array([[0],
       [3],
       [6]])

<div class="alert alert-info">
    
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

<div class="alert alert-info">
    
**Ejercicio**:
<ul>
    
<li> Cree un arreglo $3\times4\times5$, con $1$s. </li>
<li> Usando **slicing** , obtenga la columna de enmedio. </li>
<li> Usando *indexing*, obtenga el valor del elemento $[3,4,1]$. </li>
<li> Usando *slicing*, asigne el valor `1.34` a la $[2,3,]$ ¿Qué paso debe de hacer antes? </li>
</ul>
</div>

In [123]:
ejem = np.arange(60).reshape(3,4,5)
ejem

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [124]:
ejem_slice = ejem[:,:,2] 
ejem_slice

array([[ 2,  7, 12, 17],
       [22, 27, 32, 37],
       [42, 47, 52, 57]])

In [125]:
ejem_float = ejem.astype(np.float16)

In [127]:
ejem_float[2,3,] = 1.34
ejem_float

array([[[ 0.  ,  1.  ,  2.  ,  3.  ,  4.  ],
        [ 5.  ,  6.  ,  7.  ,  8.  ,  9.  ],
        [10.  , 11.  , 12.  , 13.  , 14.  ],
        [15.  , 16.  , 17.  , 18.  , 19.  ]],

       [[20.  , 21.  , 22.  , 23.  , 24.  ],
        [25.  , 26.  , 27.  , 28.  , 29.  ],
        [30.  , 31.  , 32.  , 33.  , 34.  ],
        [35.  , 36.  , 37.  , 38.  , 39.  ]],

       [[40.  , 41.  , 42.  , 43.  , 44.  ],
        [45.  , 46.  , 47.  , 48.  , 49.  ],
        [50.  , 51.  , 52.  , 53.  , 54.  ],
        [ 1.34,  1.34,  1.34,  1.34,  1.34]]], dtype=float16)

In [129]:
np.may_share_memory(ejem,ejem_float)

False

In [130]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
index = arr > 2

In [133]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [134]:
arr[index]

array([3, 4, 5, 6, 7, 8])

In [135]:
arr2 = arr[index]

In [136]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
arr2

array([3, 4, 5, 6, 7, 8])

<div class="alert alert-info">
    
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [138]:
arr = np.ones((5,4))

In [145]:
for i in range(5):
    arr[i]= i

In [146]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [141]:
arr[[4,3,1,2]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [147]:
arr[[-3,-2,-1]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [158]:
arr = np.arange(-10,10)

In [150]:
arr = -1*arr

In [151]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [152]:
arr = np.abs(arr)

In [153]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [155]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [156]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [160]:
np.logical_not(arr)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False])

In [163]:
if 10 : 
    print("Hello there")
else:
    print("General Kenobi!")

Hello there


In [164]:
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [165]:
arr = np.random.randn(10)

In [166]:
arr

array([-1.29540561, -0.33483306,  0.33505345,  1.0249452 , -0.86661063,
       -0.80060485, -0.56134789,  1.34311524, -0.80544204, -1.01801057])

In [167]:
np.ceil(arr)

array([-1., -0.,  1.,  2., -0., -0., -0.,  2., -0., -1.])

In [168]:
np.floor(arr)

array([-2., -1.,  0.,  1., -1., -1., -1.,  1., -1., -2.])

In [169]:
np.rint(arr)

array([-1., -0.,  0.,  1., -1., -1., -1.,  1., -1., -1.])

In [170]:
arr2 = np.ones(10)

In [171]:
np.add(arr, arr2)

array([-0.29540561,  0.66516694,  1.33505345,  2.0249452 ,  0.13338937,
        0.19939515,  0.43865211,  2.34311524,  0.19455796, -0.01801057])

In [172]:
np.multiply(arr, arr2)

array([-1.29540561, -0.33483306,  0.33505345,  1.0249452 , -0.86661063,
       -0.80060485, -0.56134789,  1.34311524, -0.80544204, -1.01801057])

In [173]:
np.maximum(arr, arr2)

array([1.        , 1.        , 1.        , 1.0249452 , 1.        ,
       1.        , 1.        , 1.34311524, 1.        , 1.        ])

In [174]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [175]:
arr

array([-1.29540561, -0.33483306,  0.33505345,  1.0249452 , -0.86661063,
       -0.80060485, -0.56134789,  1.34311524, -0.80544204, -1.01801057])

In [176]:
arr.sum()

-2.979140744908508

In [177]:
arr.mean()

-0.2979140744908508

In [178]:
arr = np.random.randn(5,4)

In [179]:
arr

array([[-1.63559099, -0.53921996,  0.33552737, -1.56084067],
       [-1.11953312,  1.1171936 , -0.26832605, -0.58340328],
       [ 1.25162041,  1.80524461, -1.4038944 , -1.56651372],
       [-0.38168067, -0.68620499,  1.17918652, -0.26877546],
       [ 0.49020027,  0.85436492,  1.19822985, -1.36667513]])

In [180]:
arr.sum()

-3.149090881706977

In [181]:
arr.mean()

-0.15745454408534884

In [184]:
arr.sum(0)

array([-1.39498409,  2.55137818,  1.04072329, -5.34620826])

In [187]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [188]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [195]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [196]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [197]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [198]:
(arr > 5).sum()

4

## Operaciones de conjuntos

In [199]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [201]:
np.unique(arr2)

array([1.])

In [202]:
np.intersect1d(arr, arr2)

array([1.])

## Casting

In [221]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [222]:
a +1.2

array([2.2, 3.2, 4.2])

La asignación **no** cambia el tipo del arreglo.

In [223]:
a.dtype

dtype('int64')

In [224]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

In [225]:
 np.iinfo(np.int32).max, 2**31 - 1   # Prueba con 8, 16, 32 y 64 bits

(2147483647, 2147483647)

<div class="alert alert-info">
    
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [228]:
np.finfo(np.float64).max 

1.7976931348623157e+308

In [229]:
np.finfo(np.float64).eps

2.220446049250313e-16

In [230]:
np.float32(1e-8) + np.float32(1) == 1

True

In [231]:
np.float64(1e-8) + np.float64(1) == 1

False

## Estructura de datos

In [232]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [233]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [238]:
muestra.ndim

1

In [239]:
muestra.shape

(6,)

In [241]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [242]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [243]:
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [244]:
muestra.shape

(6,)

In [245]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [246]:
muestra[0]['valor']

0.37

In [247]:
muestra[['codigo', 'valor']]

array([(b'ALFA', 0.37), (b'BETA', 0.11), (b'TAU', 0.13), (b'ALFA', 0.37),
       (b'ALFA', 0.11), (b'TAU', 0.13)],
      dtype={'names':['codigo','valor'], 'formats':['S4','<f8'], 'offsets':[0,12], 'itemsize':20})

In [251]:
muestra[muestra['codigo'] == b'ALFA']

array([(b'ALFA', 1. , 0.37), (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
    
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [252]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [253]:
x + 3

array([3, 4, 5, 6])

### 2D

<img src="images/broadcasting_2d.png"/>

In [254]:
a = np.arange(12).reshape((3,4))
print (a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [255]:
b = np.array([1,2,3])
print (b.shape)
b

(3,)


array([1, 2, 3])

In [256]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

<div class="alert alert-danger">
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [257]:
b = b[:, np.newaxis]
print (b.shape)
b

(3, 1)


array([[1],
       [2],
       [3]])

In [258]:
a + b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])