In [2]:
import numpy as np


In [16]:
z = np.zeros(4)
z


array([0., 0., 0., 0.])

In [17]:
z[1] = 3
z[1]

3.0

In [18]:
x0 = [1,1,1,1]
n = len(x0)
n


4

funcion cuadrados: 

$\begin{array}{ccc}
f:[x_1, x_2, x_3] 
\end{array} \to \mathbf{R} \\$ 
$ f(x_1,x_2,x_3) = x_1^2 + x_2^2 + x_3^2$


In [62]:

def cuadrados(x):
    resultado=0
    for i in range(len(x)):
        resultado += x[i]**2
    return resultado


función gradiente

$\nabla f = [ \frac{\partial f}{\partial x_1},  \frac{\partial f}{\partial x_2},  \frac{\partial f}{\partial x_3}]$ 

la aproximación de la primera derivada con respecto a x de una función $f(x,y)$ esta dada por 
$  \frac{\partial f}{\partial x} \approx \frac{f(x + \Delta x, y) - f(x, y)}{\Delta x} $

La diferencia finita central es a menudo más exacta: 

$  \frac{\partial f}{\partial x} \approx \frac{f(x + \frac{1}{2}\Delta x, y) - f(x-\frac{1}{2}\Delta x, y)}{\Delta x} $

en este caso $ \frac{\Delta x}{2}  $ equivale a  `z[i] = h/2`

In [63]:
def gradiente(f, x0, h=1e-6, i=-1):
    """
    Función que calcula el Grad de una función en un punto
    """
    n = len(x0)
    if i in range(n):
        z = np.zeros(n)
        z[i] = h/2
        Grad = (f(x0 + z) - f(x0 - z))/h
    else:
        Grad=np.zeros(n) #vector [0,0,0]
        for j in range(n):
            z = np.zeros(n)
            z[j] = h/2
            Grad[j]= (f(x0 + z) - f(x0 - z))/h
    return Grad

Explicacion:

In [64]:
x0 = [0,0,0]
h=3
n = len(x0)

for j in range(n):
    z = np.zeros(n)
    z[j] = h/2
    print(z)
print(z)

[1.5 0.  0. ]
[0.  1.5 0. ]
[0.  0.  1.5]
[0.  0.  1.5]


In [70]:
x = [1,1,1]
y = [3,3,3]
w = x + y
w
cuadrados(x + y)

30

necesitamos $  \frac{\partial f}{\partial x} \approx \frac{f(x + \frac{1}{2}\Delta x, y) - f(x-\frac{1}{2}\Delta x, y)}{\Delta x} $ y dada la construccion de la funcion Grad, y al construir z de esta forma se cumple esta operacion

In [112]:
x0 = [1,2,3]
h=3
n = len(x0)
Grad=np.zeros(n)
for j in range(n):
    z = np.zeros(n)
    z[j] = h/2
    print(z)
    Grad[j] = (cuadrados(x0 + z) - cuadrados(x0 - z))/h #"esto emula: f(x1 + 1/2h, x2,x3) para j = 0
    print("notemos que el solo el", (j+1), " elemento se modifica: ")
    print("res: ",(cuadrados(x0 + z) - cuadrados(x0 - z))/h)
    

print("\n esto es un vector", Grad)

[1.5 0.  0. ]
notemos que el solo el 1  elemento se modifica: 
res:  2.0
[0.  1.5 0. ]
notemos que el solo el 2  elemento se modifica: 
res:  4.0
[0.  0.  1.5]
notemos que el solo el 3  elemento se modifica: 
res:  6.0

 esto es un vector [2. 4. 6.]


Condiciones de Primer Orden
Si $x^*$ es un mínimo local y $f$ es continua diferenciable en una vecindad de $x^*$ entonces $ \nabla f(x^*) = 0$

In [ ]:
def f_o_c(f,x, tol=1e-12):
    """
    Función que calcula las condiciones de primer orden
    """
    grad = np.array(gradiente(f,x))
    if np.dot(grad, grad) < tol:
        return True
    else :
        return False

In [114]:
z = np.ones((3,4))

In [115]:
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [118]:
np.empty((2,3,4))

array([[[2.31584178e+077, 2.31584178e+077, 6.94485689e-310,
         6.94485690e-310],
        [6.94485690e-310, 6.94485690e-310, 6.94485690e-310,
         6.94485690e-310],
        [6.94485690e-310, 6.94485690e-310, 6.94485690e-310,
         6.94485690e-310]],

       [[6.94485690e-310, 6.94485690e-310, 6.94485690e-310,
         6.94485690e-310],
        [6.94485690e-310, 6.94485690e-310, 6.94485690e-310,
         6.94485690e-310],
        [6.94485690e-310, 6.94485690e-310, 6.94485690e-310,
         6.94485690e-310]]])

In [14]:
arreglo = np.arange(10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.zeros((2,4))  #returns a tuple with each index having the number of corresponding elements
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
x = np.ones((2, 3, 4, 5))
np.transpose(x)

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [