# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [1]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
lst[2:3]

[3]

In [5]:
arr[2:3]

array([3])

In [6]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [7]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr[-1] = 1.23234
arr

array([1, 2, 3, 4, 1])

In [10]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [11]:
adoring_bootharr = np.arange(1e7)  

In [12]:
lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [13]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [14]:
%timeit arr * 1.1

1.57 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit lst_multiplicacion(lst, 1.1)

717 ns ± 98.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creación de arrays

In [18]:
arr

array([1, 2, 3, 4, 1])

In [19]:
arr = np.arange(10,21)

In [20]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr = np.zeros(5)

In [4]:
arr

array([0., 0., 0., 0., 0.])

In [10]:
x = [1,2,2,3,3,2]
z = np.zeros(len(x)) + 1
z
A = np.eye(6)
A
A@z
z@A@z

6.0

In [ ]:
arr = np.linspace(0,1,100)

In [ ]:
arr

In [21]:
arr = np.logspace(0,1,100, base=10)

In [22]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [23]:
arr2d = np.zeros((5,5))

In [25]:
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [27]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [29]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [30]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [28]:
cubo.dtype

dtype('int64')

In [ ]:
np.empty((2,3,4))

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(3)

array([0.7001203 , 0.61258848, 0.44359008])

## Reshaping

In [28]:
arr = np.arange(1000)

In [31]:
arr3d = arr.reshape((10,10,10))
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [30]:
arr3d.ndim

3

In [ ]:
arr3d.shape

In [ ]:
arr3d

In [ ]:
arr = np.arange(200)

In [ ]:
arr2d = arr.reshape((10,20))

In [ ]:
arr2d

## Aplanar

In [4]:
arr = np.zeros((4,4,4,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [6]:
arr.shape #

(4, 4, 4, 4)

### ravel 
Return a contiguous flattened array.

[enlace](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)

In [16]:
arr_plano = arr.ravel()

In [ ]:
arr_plano.shape

In [ ]:
arr_plano

## *Broadcasting*

In [17]:
data = np.array([1,2,3,4,5])

In [11]:
data

array([1, 2, 3, 4, 5])

In [12]:
data + 1

array([2, 3, 4, 5, 6])

In [13]:
data * 2

array([ 2,  4,  6,  8, 10])

In [14]:
data ** 2

array([ 1,  4,  9, 16, 25])

In [24]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [51]:
arr  = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [52]:
arr  = np.arange(16).reshape((2,4,2)).shape
arr

(2, 4, 2)

In [62]:
arr  = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [63]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [4]:
arr_slice =  arr[5:8]
arr_slice

array([5, 6, 7])

In [5]:
arr_slice[1]= 12345678
arr_slice

array([       5, 12345678,        7])

In [6]:
arr
arr_slice[:] = 345
arr_slice

array([345, 345, 345])

In [7]:
arr #Array modificado

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

### numpy.copy
Return an array copy of the given object.
[documentacion](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

In [9]:
arr2 = np.copy(arr) ##copia el arreglo ya no modifica arr
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [10]:
arr2[5:8] = [5,6,7]
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [12]:
np.may_share_memory(arr, arr_slice)

True

In [13]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

<div class="alert alert-info">
    
**Slicing**:
Slicing in python means taking elements from one given index to another given index.
    
define the step, like this: **[start:end:step]**
    <ul>
    <li> If we don't pass start its considered 0
    <li> If we don't pass end its considered length of array in that dimension
    <li> If we don't pass step its considered 
    </ul>
</div>

In [20]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr.ndim

1

In [22]:
arr.shape = (3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr.ndim

2

In [26]:
y = np.zeros((2, 3, 4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
y.ndim

3

In [30]:
arr[2]

array([6, 7, 8])

In [31]:
arr[-1]

array([6, 7, 8])

In [32]:
arr[1][1]

4

In [33]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [36]:
arr[:3] # todo el arreglo

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr[:1,:3] #primer renglon hasta la columna 3

array([[0, 1, 2]])

In [38]:
arr[1:,:2] #a partir del segundo renglon, hasta la columan 2

array([[3, 4],
       [6, 7]])

In [39]:
arr[1:,] #a partir del segundo renglon, todas las columnas

array([[3, 4, 5],
       [6, 7, 8]])

In [40]:
arr[1,:2] #segundo renglon, la dos primeras columnas

array([3, 4])

In [41]:
arr[1,2:] #segundo renglon, de la columna 3 en adelante

array([5])

In [45]:
arr[:,1:] #todos los renglones, a partir de la segunda columna en adelnate

array([[1, 2],
       [4, 5],
       [7, 8]])

<div class="alert alert-info">
    
**Ejercicio**:
<ul>
    
<li> Cree un arreglo $3\times4\times5$, con $1$s. </li>
<li> Usando **slicing** , obtenga la columna de enmedio. </li>
<li> Usando *indexing*, obtenga el valor del elemento $[3,4,1]$. </li>
<li> Usando *slicing*, asigne el valor `1.34` a la $[2,3,]$ ¿Qué paso debe de hacer antes? </li>
</ul>
</div>

In [48]:
ejem = np.arange(60).reshape(3,4,5)
ejem

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [49]:
ejem_slice = ejem[:,:,2]  #columna de enmedio 
ejem_slice

array([[ 2,  7, 12, 17],
       [22, 27, 32, 37],
       [42, 47, 52, 57]])

In [57]:
ejem[2,3,0] # valor del elemento [3,4,1]  (ejem[2,3,0] 3er bloque, 4to renglon,1era columna)

55

In [51]:
ejem_float = ejem.astype(np.float16)

In [58]:
ejem_float[2,3,] = 1.34
ejem_float

array([[[ 0.  ,  1.  ,  2.  ,  3.  ,  4.  ],
        [ 5.  ,  6.  ,  7.  ,  8.  ,  9.  ],
        [10.  , 11.  , 12.  , 13.  , 14.  ],
        [15.  , 16.  , 17.  , 18.  , 19.  ]],

       [[20.  , 21.  , 22.  , 23.  , 24.  ],
        [25.  , 26.  , 27.  , 28.  , 29.  ],
        [30.  , 31.  , 32.  , 33.  , 34.  ],
        [35.  , 36.  , 37.  , 38.  , 39.  ]],

       [[40.  , 41.  , 42.  , 43.  , 44.  ],
        [45.  , 46.  , 47.  , 48.  , 49.  ],
        [50.  , 51.  , 52.  , 53.  , 54.  ],
        [ 1.34,  1.34,  1.34,  1.34,  1.34]]], dtype=float16)

In [59]:
np.may_share_memory(ejem,ejem_float)

False

In [60]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
index = arr > 2 #compara el valor de cada uno de los elementos de la matriz

In [62]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [63]:
arr[index] ##solo regresa los valores que cumplen esa condicion

array([3, 4, 5, 6, 7, 8])

In [64]:
arr2 = arr[index]

In [65]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
arr2

array([3, 4, 5, 6, 7, 8])

## Fancy Indexing

otra forma de indexar los valores en los arreglos

por ejemplo:
`arr[[4,3,1,2]]` agrega esos valores que estan dentro del rango que definimos en el for en los renglones correspondientes 

In [67]:
arr = np.ones((5,4))

In [68]:
for i in range(5):
    arr[i]= i

In [69]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [77]:
arr[[4,3,1,0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [83]:
arr[[-5,-2,-1]] #hace lo mismo pero la cuenta es al reves -5 equiv a 0 en el range(5)

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [85]:
arr = np.arange(-10,10)
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [86]:
arr = -1*arr
arr

In [89]:
arr = np.abs(arr)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [90]:
np.sqrt(arr)

array([3.16227766, 3.        , 2.82842712, 2.64575131, 2.44948974,
       2.23606798, 2.        , 1.73205081, 1.41421356, 1.        ,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#### sign function
The sign function returns -1 if x < 0, 0 if x==0, 1 if x > 0. nan is returned for nan inputs.

In [91]:
np.sign(arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [92]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [93]:
np.logical_not(arr)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False])

In [94]:
if 10 : 
    print("Hello there")
else:
    print("General Kenobi!")

Hello there


In [95]:
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

#### np.random.randn
Return a sample (or samples) from the “standard normal” distribution.

In [97]:
arr = np.random.randn(10)
arr

array([ 0.44817174,  0.2688145 ,  1.06279268, -0.32219485,  1.10664907,
       -0.09104684, -0.44734364,  1.19400639, -1.01287194, -0.27688706])

In [98]:
np.ceil(arr)

array([ 1.,  1.,  2., -0.,  2., -0., -0.,  2., -1., -0.])

In [99]:
np.floor(arr)

array([ 0.,  0.,  1., -1.,  1., -1., -1.,  1., -2., -1.])

#### np.rint
Round elements of the array to the nearest integer.

In [101]:
np.rint(arr)

array([ 0.,  0.,  1., -0.,  1., -0., -0.,  1., -1., -0.])

In [108]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [109]:
np.add(arr, arr2)

array([ 1.44817174,  1.2688145 ,  2.06279268,  0.67780515,  2.10664907,
        0.90895316,  0.55265636,  2.19400639, -0.01287194,  0.72311294])

In [104]:
np.multiply(arr, arr2)

array([ 0.44817174,  0.2688145 ,  1.06279268, -0.32219485,  1.10664907,
       -0.09104684, -0.44734364,  1.19400639, -1.01287194, -0.27688706])

In [105]:
np.maximum(arr, arr2)

array([1.        , 1.        , 1.06279268, 1.        , 1.10664907,
       1.        , 1.        , 1.19400639, 1.        , 1.        ])

#### logical_and
Compute the truth value of x1 AND x2 element-wise.

In [110]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [112]:
arr

array([ 0.44817174,  0.2688145 ,  1.06279268, -0.32219485,  1.10664907,
       -0.09104684, -0.44734364,  1.19400639, -1.01287194, -0.27688706])

In [113]:
arr.sum()

1.9300900370633494

In [114]:
arr.mean()

0.19300900370633495

In [115]:
arr = np.random.randn(5,4)

In [116]:
arr

array([[ 1.74289867, -1.75208379, -0.37138671,  0.69098622],
       [ 1.79846981,  0.13121277, -1.34238653, -2.5429911 ],
       [-1.06003462, -1.33311921, -0.76315221, -0.32857444],
       [ 0.0766646 , -2.11429369,  0.79411442, -1.24837573],
       [ 0.83934557, -1.50148128, -0.31678545,  1.1069382 ]])

In [117]:
arr.sum()

-7.494034485325793

In [118]:
arr.mean()

-0.37470172426628967

In [119]:
arr.sum(0)

array([ 3.39734402, -6.5697652 , -1.99959648, -2.32201683])

In [120]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### numpy.cumsum
`numpy.cumsum(a, axis=None, dtype=None, out=None)`

Return the cumulative sum of the elements along a given axis.

In [121]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [122]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [123]:
arr.reshape(2,5) #2 columnas, subgrupos de 5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [125]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [126]:
(arr > 5).sum()

4

## Operaciones de conjuntos

In [128]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### numpy.unique
`numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)` 

Find the unique elements of an array.



In [130]:
np.unique(arr2)

array([1.])

#### numpy.intersect1d
`numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)` 

Find the intersection of two arrays.



In [132]:
np.intersect1d(arr, arr2)

array([1.])

## Casting

In [134]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [135]:
a +1.2

array([2.2, 3.2, 4.2])

In [138]:
a

array([1, 2, 3])

La asignación **no** cambia el tipo del arreglo.

In [136]:
a.dtype

dtype('int64')

In [137]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

`class numpy.iinfo(type)`

Machine limits for integer types.

In [141]:
print(np.iinfo(np.int32).max, 2**31 - 1)   # Prueba con 8, 16, 32 y 64 bits
print(np.iinfo(np.int64).max, 2**31 - 1) 
print(np.iinfo(np.int).max, 2**31 - 1) 

2147483647 2147483647
9223372036854775807 2147483647
9223372036854775807 2147483647


`class numpy.finfo(dtype)`

Machine limits for floating point types.

In [ ]:
np.finfo(np.float64).max 

In [142]:
np.finfo(np.float64).eps

2.220446049250313e-16

In [143]:
np.float32(1e-8) + np.float32(1) == 1

True

In [ ]:
np.float64(1e-8) + np.float64(1) == 1

## Estructura de datos

In [147]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [148]:
muestra

array([(b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.), (b'', 0., 0.),
       (b'', 0., 0.), (b'', 0., 0.)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [149]:
muestra.ndim

1

In [150]:
muestra.shape

(6,)

In [151]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [153]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [154]:
muestra

array([(b'ALFA', 1. , 0.37), (b'BETA', 1. , 0.11), (b'TAU', 1. , 0.13),
       (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11), (b'TAU', 1.2, 0.13)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [155]:
muestra.shape

(6,)

In [156]:
muestra['codigo']

array([b'ALFA', b'BETA', b'TAU', b'ALFA', b'ALFA', b'TAU'], dtype='|S4')

In [157]:
muestra[0]['valor']

0.37

In [158]:
muestra[['codigo', 'valor']]

array([(b'ALFA', 0.37), (b'BETA', 0.11), (b'TAU', 0.13), (b'ALFA', 0.37),
       (b'ALFA', 0.11), (b'TAU', 0.13)],
      dtype={'names':['codigo','valor'], 'formats':['S4','<f8'], 'offsets':[0,12], 'itemsize':20})

In [162]:
muestra[muestra['codigo'] == b'ALFA']

array([(b'ALFA', 1. , 0.37), (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11)],
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
    
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png" width = 300 height = 300 />


In [ ]:
x = np.arange(4)
x

In [ ]:
x + 3

### 2D

<img src="images/broadcasting_2d.png" width = 280 height = 280 />

In [163]:
a = np.arange(12).reshape((3,4))
print (a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
b = np.array([1,2,3])
print (b.shape)
b

(3,)


array([1, 2, 3])

In [166]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

<div class="alert alert-danger">
    
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

`numpy.newaxis`
 is used to increase the dimension of the existing array by one more dimension, when used once.

<img src="images/newaxis.png" width="400" height="400"/>

In [169]:
b = b[:, np.newaxis]
print (b.shape)
b

(3, 1, 1)


array([[[1]],

       [[2]],

       [[3]]])

In [170]:
a + b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]]])