# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012

In [2]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
lst[2:3]

[3]

In [5]:
arr[2:3]

array([3])

In [6]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [7]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for int() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr[-1] = 1.23234
arr

array([1, 2, 3, 4, 1])

In [10]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [11]:
adoring_bootharr = np.arange(1e7)  

In [12]:
lst = arr.tolist()

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [13]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val
    return alist

In [14]:
%timeit arr * 1.1

1.57 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit lst_multiplicacion(lst, 1.1)

717 ns ± 98.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creación de arrays

In [18]:
arr

array([1, 2, 3, 4, 1])

In [19]:
arr = np.arange(10,21)

In [20]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr = np.zeros(5)

In [4]:
arr

array([0., 0., 0., 0., 0.])

In [10]:
x = [1,2,2,3,3,2]
z = np.zeros(len(x)) + 1
z
A = np.eye(6)
A
A@z
z@A@z

6.0

In [ ]:
arr = np.linspace(0,1,100)

In [ ]:
arr

In [21]:
arr = np.logspace(0,1,100, base=10)

In [22]:
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [23]:
arr2d = np.zeros((5,5))

In [25]:
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [27]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [29]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [30]:
cubo

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [28]:
cubo.dtype

dtype('int64')

In [ ]:
np.empty((2,3,4))

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(3)

array([0.7001203 , 0.61258848, 0.44359008])

## Reshaping

In [28]:
arr = np.arange(1000)

In [31]:
arr3d = arr.reshape((10,10,10))
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [30]:
arr3d.ndim

3

In [ ]:
arr3d.shape

In [ ]:
arr3d

In [ ]:
arr = np.arange(200)

In [ ]:
arr2d = arr.reshape((10,20))

In [ ]:
arr2d

## Aplanar

In [ ]:
arr = np.zeros((4,4,4,4))

In [ ]:
arr.shape

In [ ]:
arr_plano = arr.ravel()

In [ ]:
arr_plano.shape

In [ ]:
arr_plano

## *Broadcasting*

In [ ]:
data = np.array([1,2,3,4,5])

In [ ]:
data

In [ ]:
data + 1

In [ ]:
data * 2

In [ ]:
data ** 2

## Transponer

In [ ]:
arr = np.arange(15).reshape((3,5))

In [ ]:
arr

In [ ]:
arr.T

¿Qué pasa en varias dimensiones?

In [ ]:
arr  = np.arange(16).reshape((2,2,4))

In [ ]:
arr

In [ ]:
arr.transpose((1,0,2))

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [ ]:
arr = np.arange(10)

In [ ]:
arr

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [ ]:
arr_slice =  arr[5:8]

In [ ]:
arr_slice

In [ ]:
arr_slice[1]= 12345678

In [ ]:
arr_slice

In [ ]:
arr

In [ ]:
arr_slice[:] = 345

In [ ]:
arr_slice

In [ ]:
arr

In [ ]:
arr2 = np.copy(arr)

In [ ]:
arr2

In [ ]:
arr2[5:8] = [5,6,7]

In [ ]:
arr2

In [ ]:
arr

In [ ]:
np.may_share_memory(arr, arr_slice)

In [ ]:
np.may_share_memory(arr, arr2)

### Multidimensional

In [ ]:
arr = np.arange(9)

In [ ]:
arr.shape = (3,3)

In [ ]:
arr

In [ ]:
arr.ndim

In [ ]:
arr[2]

In [ ]:
arr[-1]

In [ ]:
arr[1][1]

In [ ]:
arr[1:]

In [ ]:
arr[:2]

In [ ]:
arr[:1,:2]

In [ ]:
arr[1:,:2]

In [ ]:
arr[1:,]

In [ ]:
arr[1,:2]

In [ ]:
arr[1,2:]

In [ ]:
arr[:,1:]

In [ ]:
arr[:,:1] 1,  1,  1,  1,  1]

<div class="alert alert-info">
    
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

<div class="alert alert-info">
    
**Ejercicio**:
<ul>
    
<li> Cree un arreglo $3\times4\times5$, con $1$s. </li>
<li> Usando **slicing** , obtenga la columna de enmedio. </li>
<li> Usando *indexing*, obtenga el valor del elemento $[3,4,1]$. </li>
<li> Usando *slicing*, asigne el valor `1.34` a la $[2,3,]$ ¿Qué paso debe de hacer antes? </li>
</ul>
</div>

In [ ]:
ejem = np.arange(60).reshape(3,4,5)
ejem

In [ ]:
ejem_slice = ejem[:,:,2] 
ejem_slice

In [ ]:
ejem_float = ejem.astype(np.float16)

In [ ]:
ejem_float[2,3,] = 1.34
ejem_float

In [ ]:
np.may_share_memory(ejem,ejem_float)

In [ ]:
arr

In [ ]:
index = arr > 2

In [ ]:
index

In [ ]:
arr[index]

In [ ]:
arr2 = arr[index]

In [ ]:
arr

In [ ]:
arr2

<div class="alert alert-info">
    
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [ ]:
arr = np.ones((5,4))

In [ ]:
for i in range(5):
    arr[i]= i

In [ ]:
arr

In [ ]:
arr[[4,3,1,2]]

In [ ]:
arr[[-3,-2,-1]]

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [ ]:
arr = np.arange(-10,10)

In [ ]:
arr = -1*arr

In [ ]:
arr

In [ ]:
arr = np.abs(arr)

In [ ]:
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.sign(arr)

In [ ]:
np.isfinite(arr)

In [ ]:
np.logical_not(arr)

In [ ]:
if 10 : 
    print("Hello there")
else:
    print("General Kenobi!")

In [ ]:
arr

In [ ]:
arr = np.random.randn(10)

In [ ]:
arr

In [ ]:
np.ceil(arr)

In [ ]:
np.floor(arr)

In [ ]:
np.rint(arr)

In [ ]:
arr2 = np.ones(10)

In [ ]:
np.add(arr, arr2)

In [ ]:
np.multiply(arr, arr2)

In [ ]:
np.maximum(arr, arr2)

In [ ]:
np.logical_and(arr, arr2)

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr = np.random.randn(5,4)

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.sum(0)

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr.cumsum()

In [ ]:
arr.cumprod()

In [ ]:
arr.reshape(2,5)

In [ ]:
arr.cumsum()

In [ ]:
arr > 5

In [ ]:
(arr > 5).sum()

## Operaciones de conjuntos

In [ ]:
arr

In [ ]:
arr2

In [ ]:
np.unique(arr2)

In [ ]:
np.intersect1d(arr, arr2)

## Casting

In [ ]:
a = np.array([1,2,3])
a

El tipo de mayor jerarquía define el _cast_

In [ ]:
a +1.2

La asignación **no** cambia el tipo del arreglo.

In [ ]:
a.dtype

In [ ]:
(a + 1.5).dtype

## Tipos 

In [ ]:
 np.iinfo(np.int32).max, 2**31 - 1   # Prueba con 8, 16, 32 y 64 bits

<div class="alert alert-info">
    
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [ ]:
np.finfo(np.float64).max 

In [ ]:
np.finfo(np.float64).eps

In [ ]:
np.float32(1e-8) + np.float32(1) == 1

In [ ]:
np.float64(1e-8) + np.float64(1) == 1

## Estructura de datos

In [ ]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [ ]:
muestra

In [ ]:
muestra.ndim

In [ ]:
muestra.shape

In [ ]:
muestra.dtype.names

In [ ]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [ ]:
muestra

In [ ]:
muestra.shape

In [ ]:
muestra['codigo']

In [ ]:
muestra[0]['valor']

In [ ]:
muestra[['codigo', 'valor']]

In [ ]:
muestra[muestra['codigo'] == b'ALFA']

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
    
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [ ]:
x = np.arange(4)
x

In [ ]:
x + 3

### 2D

<img src="images/broadcasting_2d.png"/>

In [ ]:
a = np.arange(12).reshape((3,4))
print (a.shape)
a

In [ ]:
b = np.array([1,2,3])
print (b.shape)
b

In [ ]:
a+b

<div class="alert alert-danger">
    
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [ ]:
b = b[:, np.newaxis]
print (b.shape)
b

In [ ]:
a + b